/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chat.gui;

import chat.logic.ChatManager;
import chat.logic.MessageListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLDocument;

/**
 *
 * @author Luca
 */
public class ChatPanel extends javax.swing.JPanel implements MessageListener {

    private String username = "NO_USERNAME";

    /**
     * Creates new form ChatPanel
     */
    public ChatPanel() {
        initComponents();
        this.username = jTextField_username.getText();
        this.jTextPane_chat.setContentType("text/html");
        ChatManager.getInstance().addMessageListener(this);
    }

    public void connetti() {
        //instanzio il Htread per le connessioni: byneri nassuni giocatori = 10
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane_input = new javax.swing.JEditorPane();
        jButton_send = new javax.swing.JButton();
        jTextField_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane_chat = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(102, 102, 255));

        jEditorPane_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jEditorPane_inputKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jEditorPane_inputKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jEditorPane_input);

        jButton_send.setText("Send >");
        jButton_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sendActionPerformed(evt);
            }
        });

        jTextField_username.setText("inserire qui un username");
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:");

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jTextPane_chat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_send))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_send, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sendActionPerformed
        ChatManager.getInstance().newMessage(this.username, this.jEditorPane_input.getText());
        this.jEditorPane_input.setText("");
    }//GEN-LAST:event_jButton_sendActionPerformed

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.username = jTextField_username.getText();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jEditorPane_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEditorPane_inputKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jButton_send.doClick();
        }

    }//GEN-LAST:event_jEditorPane_inputKeyTyped

    private void jEditorPane_inputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEditorPane_inputKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jButton_send.doClick();
        }
    }//GEN-LAST:event_jEditorPane_inputKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_send;
    private javax.swing.JEditorPane jEditorPane_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JTextPane jTextPane_chat;
    // End of variables declaration//GEN-END:variables

    @Override
    public void newMessage(String user, String message) {
        if (user.equals(this.username)) {
            try {
                String s = "<b>me: </b>" + message + "<br>";
                HTMLDocument doc = (HTMLDocument) jTextPane_chat.getStyledDocument();
                doc.insertAfterEnd(doc.getCharacterElement(doc.getLength()), s);
            } catch (BadLocationException exc) {
                exc.printStackTrace();
            } catch (IOException ex) {
                Logger.getLogger(ChatPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                String s = user+": " + message + "<br>";
                HTMLDocument doc = (HTMLDocument) jTextPane_chat.getStyledDocument();
                doc.insertAfterEnd(doc.getCharacterElement(doc.getLength()), s);
            } catch (BadLocationException exc) {
                exc.printStackTrace();
            } catch (IOException ex) {
                Logger.getLogger(ChatPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
